name: data_playground
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
  sqflite: ^2.4.2
  path: ^1.9.0
  dio: ^5.9.0
  retrofit: ^4.8.0
  json_annotation: ^4.9.0
  floor: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true
